### ISSUE TITLE
Plugin fails to install on Idea 13

### ISSUE THREAD

**Issue by vvandens** [setial/intellij-javadocs#24] opened 2013-12-04 08:49 UTC
First of all, I love this plugin. Thanks !
Unfortunately, it fails to install on latest idea 13 that has just been released.
The exception is :

Plugin JavaDoc was not installed: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

**Comment by TSergey** [comment] 2015-12-25 12:20
Closing since there is some kind of workaround and it looks like the problem is related to environment.

**Closed by TSergey** 2015-12-25 12:20 UTC
